"""Per-customer expected-cost model.

A flat false-negative:false-positive ratio (the usual portfolio shortcut) treats a
customer who owes NT$2,000 the same as one who owes NT$800,000. Real risk teams do not
do this, and neither does this module: every cost is computed per row from that
customer's own exposure, so the "optimal threshold" is a genuine per-customer number,
not one global cutoff dressed up as one.

Three assumptions drive the whole model, all exposed as CLI flags so the sensitivity
table in the README is regenerated by ``fraud-calibrated sensitivity``, not hand-typed:

* ``lgd`` -- loss given default, the fraction of exposure actually lost when a customer
  who was let through does default. 0.75 by default (recovery costs eat the rest).
* ``intervention_cost`` -- fixed NT$ cost of flagging a customer for manual review or a
  credit-limit cut, whether or not they were actually going to default.
* ``margin_rate`` -- the interest/fee margin forgone on a good customer who gets flagged
  and has their limit cut, as a fraction of exposure.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class CostModel:
    """NT$ cost parameters. All three are stated assumptions -- see module docstring."""

    lgd: float = 0.75
    intervention_cost: float = 500.0
    margin_rate: float = 0.05

    def __post_init__(self) -> None:
        for name, value in (("lgd", self.lgd), ("margin_rate", self.margin_rate)):
            if not 0.0 <= value <= 1.0:
                raise ValueError(f"{name} must be in [0, 1], got {value}")
        if self.intervention_cost < 0:
            raise ValueError("intervention_cost must be non-negative")

    def cost_matrix(self, exposure: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """Per-row cost of a false negative and a false positive.

        False negative (defaulter let through): the bank loses ``lgd`` of exposure.
        False positive (good customer flagged): the bank forgoes ``margin_rate`` of
        exposure plus the fixed intervention cost -- it does not lose the exposure
        itself, since the customer did not actually default.
        """
        exposure = np.asarray(exposure, dtype=float)
        fn_cost = self.lgd * exposure
        fp_cost = self.margin_rate * exposure + self.intervention_cost
        return fn_cost, fp_cost


def optimal_threshold_per_row(
    prob_default: np.ndarray, exposure: np.ndarray, cost_model: CostModel
) -> np.ndarray:
    """The probability at which flagging and not-flagging cost the same, per row.

    Expected cost of flagging: ``fp_cost``. Expected cost of not flagging:
    ``p * fn_cost``. They are equal at ``p* = fp_cost / fn_cost`` (clipped to [0, 1] --
    a customer with near-zero exposure can have ``fp_cost > fn_cost`` at every
    probability, meaning "never flag on cost grounds alone", which the clip to 1.0
    encodes rather than hides).
    """
    fn_cost, fp_cost = cost_model.cost_matrix(exposure)
    with np.errstate(divide="ignore", invalid="ignore"):
        threshold = np.where(fn_cost > 0, fp_cost / fn_cost, 1.0)
    return np.clip(threshold, 0.0, 1.0)


def decide(prob_default: np.ndarray, exposure: np.ndarray, cost_model: CostModel) -> np.ndarray:
    """Boolean flag decision: True means intervene (deny/limit-cut/manual review)."""
    threshold = optimal_threshold_per_row(prob_default, exposure, cost_model)
    return np.asarray(prob_default) >= threshold


def realized_cost(
    y_true: np.ndarray, flagged: np.ndarray, exposure: np.ndarray, cost_model: CostModel
) -> np.ndarray:
    """Actual NT$ cost incurred per row, given the ground-truth outcome.

    A flagged defaulter or an unflagged non-defaulter costs nothing under this model --
    the bank either avoided the loss or never incurred one. Only the two mistakes cost
    money: an unflagged defaulter (the loss happens) and a flagged non-defaulter (the
    margin and intervention cost are spent for nothing).
    """
    y_true = np.asarray(y_true, dtype=bool)
    flagged = np.asarray(flagged, dtype=bool)
    fn_cost, fp_cost = cost_model.cost_matrix(exposure)
    cost = np.zeros_like(fn_cost)
    false_negative = y_true & ~flagged
    false_positive = ~y_true & flagged
    cost[false_negative] = fn_cost[false_negative]
    cost[false_positive] = fp_cost[false_positive]
    return cost


def total_cost(
    y_true: np.ndarray, flagged: np.ndarray, exposure: np.ndarray, cost_model: CostModel
) -> float:
    """Sum of :func:`realized_cost` across all rows -- the headline README number."""
    return float(realized_cost(y_true, flagged, exposure, cost_model).sum())


def global_threshold_cost(
    y_true: np.ndarray,
    prob_default: np.ndarray,
    exposure: np.ndarray,
    cost_model: CostModel,
    thresholds: np.ndarray,
) -> np.ndarray:
    """Total cost at each candidate *global* (non-per-row) threshold.

    Exists so the README can show, honestly, how much the per-row rule saves over the
    best possible single cutoff -- the baseline every other fraud-portfolio project
    reports as if it were the ceiling.
    """
    prob_default = np.asarray(prob_default)
    costs = np.empty(len(thresholds), dtype=float)
    for i, t in enumerate(thresholds):
        flagged = prob_default >= t
        costs[i] = total_cost(y_true, flagged, exposure, cost_model)
    return costs
